[build-system]
requires = ["scikit-build-core", "nanobind"]
build-backend = "scikit_build_core.build"

[project]
name = "linefit"
version = "0.2.4"
description = "linefit ground segmentation algorithm Python bindings"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "Qingwen Zhang", email = "qingwen@kth.se" }
]
classifiers = [
    "License :: OSI Approved :: BSD License",
]

[project.urls]
urls = "https://github.com/Kin-Zhang/linefit"


[tool.scikit-build]
# Protect the configuration against future changes in scikit-build-core
minimum-version = "0.4"

# Setuptools-style build caching in a local directory
build-dir = "build/{wheel_tag}"

# Build stable ABI wheels for CPython 3.12+
wheel.py-api = "cp312"


[tool.cibuildwheel]
# Necessary to see build output from the actual compilation
build-verbosity = 1

# Run pytest to ensure that the package was correctly built
test-command = "pytest {project}/tests"
test-requires = "pytest"

archs = ["auto64"]

# Needed for full C++17 support
[tool.cibuildwheel.macos.environment]
MACOSX_DEPLOYMENT_TARGET = "10.14"
